title: Comp Language
theme: minima

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE
  - design/function.md
  - design/module.md
  - design/struct.md
  - design/syntax.md
  - design/type.md
exclude:
  - src/
  - lib/
  - examples/
  - stdlib/
  - vscode/
  - pyproject.toml
  - uv.lock
  - package-lock.json
  - "**/*.comp"

