title: Comp Language
theme: minima

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE
  - design/function.md
  - design/module.md
  - design/struct.md
  - design/syntax.md
  - design/type.md
  - docs/filesystem.md
  - docs/lazy.md
  - docs/module-management.md
  - docs/path-store.md
  - docs/pure-cache.md
  - docs/store.md
  - docs/trail.md
  - docs/wrench.md
