!import /loop = comp "loop"


!func |equal-infinite ~any = {
    $var.stream = [|infinite start=5 step=2]
    $var.data = {[|:$var.stream] [|:$var.stream] [|:$var.stream]}
    $var.data {5 7 9}
}

!func |equal-range ~any = {
    $var.numbers = [|range start=2 end=10 step=3]
    $var.x = [$var.numbers |print]
    $var.numbers {2 5 8}
}

!func |equal-iter ~any = {
    $var.data = {a=10 b=20 c=30}
    $var.block = :{
        [$in |print]
        [$in.value |print]
        $in.value
    }
    $var.result = [|iter $var.data $var.block]
    $var.result {10 20 30}
}

!func |equal-subscript ~any = {
    $var.data = {x=5 y=10 z=15}
    $var.item = [$var.data |subscript index=1]
    $var.item.value 10
}