Get top weekly thumbed issues from GitHub

Based on: https://julianhofer.eu/blog/2025/nushell/#format-table-in-markdown-format
___

import.gh = {"github-api" comp}
import.time = {"core/time" stdlib}


main = :(
    var.after = time.now {} - 1~week
    var.fields = {~created-at ~title ~url ~reactions}

    gh.list-issues {repo="nushell/nushell" fields=var.fields}
    | filter :issue(issue.created-at >= var.after)
    | map :i{i | merge {
        num-thumbs = i.reactions | count :r(r.content == ~thumbs-up)
    }}
    | sort {~reverse} :i(i.num-thumbs)
    | first {5}
	| rename-fields {num-thumbs="👍"}
	| to-markdown {}
)
