; Comp version
!func main-cli = {
  !var.words = () -> stdin() -> read-lines() -> map() => split() -> flatten()
  !var.most = !var.words -> tally() -> max-field(value) => ("key")
  !var.most -> print("The most frequent word is ${}")
}

;; Nim version
;import tables, strutils
;
;var wordFrequencies = initCountTable[string]()
;
;for line in stdin.lines:
;  for word in line.split(", "):
;    wordFrequencies.inc(word)
;
;echo "The most frequent word is '", wordFrequencies.largest, "'"
