; Comp version
!main = {
  @words = (|stdin |read-lines/io |map |split |flatten)
  @most = (@words |tally |max-field value |.key)
  @most |tap {%"The most frequent word is '${$in}'" |print}
}

;; Nim version
;import tables, strutils
;
;var wordFrequencies = initCountTable[string]()
;
;for line in stdin.lines:
;  for word in line.split(", "):
;    wordFrequencies.inc(word)
;
;echo "The most frequent word is '", wordFrequencies.largest, "'"
